export {
  DEFAULT_SUPERVISION_EVENT_LOOP_LAG_MS,
  DEFAULT_SUPERVISION_INTERVAL_MS,
  DEFAULT_SUPERVISION_RSS_LIMIT_BYTES,
  DEFAULT_SUPERVISION_SUSTAINED_SAMPLES,
  createProcessSupervisor,
  nodeMemoryReader,
  type MemoryReader,
  type ProcessSupervisor,
  type ProcessSupervisorOptions,
  type ProcessSupervisorStatus,
  type SupervisionClock,
  type SupervisionCondition,
  type SupervisionLagSample,
  type SupervisionMemorySample,
} from "./process-supervision.js";
